"use client";

import { Activity, Building2, Check, Download, FileUp, RefreshCw, Repeat2, ShieldCheck, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useCurrencyFormatter } from "@/components/currency-context";

type Pattern={id:string;merchant:string;category:string;frequency:string;averageAmount:number;confidence:number;status:string};
type Upcoming={id:string;type:string;name:string;amount:number;dueDate:string};
type Subscription={id:string;name:string;vendor:string;category:string;amount:number;frequency:string;renewalDate:string;status:string};
type Bank={id:string;provider:string;displayName:string;accountId:string|null;accountName:string|null;status:string;lastSyncAt:string|null;syncLogs:Array<{id:string;status:string;transactionCount:number;syncedAt:string}>};
type Audit={id:string;actor:string;action:string;entityType:string;entityId:string;createdAt:string};
type Household={role:string;members:Array<{userId:string;name:string;email:string;role:string}>};
type Governance={deletion:{id:string;executeAfter:string}|null;transfers:Array<{id:string;fromUserId:string;toUserId:string;status:string;fromUser:{name:string|null;email:string};toUser:{name:string|null;email:string}}>};
type Account={id:string;name:string};

async function message(response:Response,fallback:string){try{const result=await response.json() as {error?:string};return result.error??fallback}catch{return fallback}}

export function OperationsWorkspace(){
 const{currency}=useCurrencyFormatter();const[tab,setTab]=useState("upcoming");const[notice,setNotice]=useState("");const[patterns,setPatterns]=useState<Pattern[]>([]);const[upcoming,setUpcoming]=useState<Upcoming[]>([]);const[subscriptions,setSubscriptions]=useState<Subscription[]>([]);const[banks,setBanks]=useState<Bank[]>([]);const[audits,setAudits]=useState<Audit[]>([]);const[household,setHousehold]=useState<Household|null>(null);const[governanceData,setGovernanceData]=useState<Governance|null>(null);const[accounts,setAccounts]=useState<Account[]>([]);
 async function load(){const[pr,rm,su,ba,au,ho,go,fp]=await Promise.all([fetch("/api/recurring-patterns"),fetch("/api/reminders"),fetch("/api/subscriptions"),fetch("/api/bank-connections"),fetch("/api/audit-logs"),fetch("/api/households"),fetch("/api/account/governance"),fetch("/api/financial-position")]);if(pr.ok)setPatterns((await pr.json()).data);if(rm.ok)setUpcoming((await rm.json()).data.upcoming);if(su.ok)setSubscriptions((await su.json()).data);if(ba.ok)setBanks((await ba.json()).data);if(au.ok)setAudits((await au.json()).data);if(ho.ok)setHousehold((await ho.json()).data);if(go.ok)setGovernanceData((await go.json()).data);if(fp.ok)setAccounts((await fp.json()).data.accounts)}
 useEffect(()=>{let active=true;void Promise.all([fetch("/api/recurring-patterns"),fetch("/api/reminders"),fetch("/api/subscriptions"),fetch("/api/bank-connections"),fetch("/api/audit-logs"),fetch("/api/households"),fetch("/api/account/governance"),fetch("/api/financial-position")]).then(async responses=>Promise.all(responses.map(response=>response.ok?response.json():null))).then(results=>{if(!active)return;setPatterns(results[0]?.data??[]);setUpcoming(results[1]?.data?.upcoming??[]);setSubscriptions(results[2]?.data??[]);setBanks(results[3]?.data??[]);setAudits(results[4]?.data??[]);setHousehold(results[5]?.data??null);setGovernanceData(results[6]?.data??null);setAccounts(results[7]?.data?.accounts??[])});return()=>{active=false}},[]);
 async function detect(){const response=await fetch("/api/recurring-patterns",{method:"POST"});if(!response.ok)return setNotice(await message(response,"Detection failed."));setNotice("Recurring analysis complete.");await load()}
 async function managePattern(id:string,action:"confirm"|"dismiss"){const response=await fetch(`/api/recurring-patterns/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});if(!response.ok)return setNotice(await message(response,"Pattern could not be updated."));await load()}
 async function addSubscription(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const response=await fetch("/api/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});if(!response.ok)return setNotice(await message(response,"Subscription could not be saved."));formElement.reset();await load()}
 async function updateSubscription(id:string,status:"active"|"paused"|"cancelled"){const response=await fetch(`/api/subscriptions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!response.ok)return setNotice(await message(response,"Subscription could not be updated."));await load()}
 async function addBank(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const response=await fetch("/api/bank-connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:form.get("provider"),externalAccountId:form.get("externalAccountId"),displayName:form.get("displayName"),accountId:form.get("accountId")||null})});if(!response.ok)return setNotice(await message(response,"Connection could not be created."));formElement.reset();await load()}
 async function importBank(connection:Bank,file:File){try{const XLSX=await import("xlsx");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,string|number>>(sheet);const transactions=rows.map((row,index)=>{const lower=Object.fromEntries(Object.entries(row).map(([key,value])=>[key.toLowerCase().trim(),value]));const amount=Number(lower.amount??0);return{externalId:String(lower.id??lower["transaction id"]??`${file.name}:${index}`),description:String(lower.description??lower.memo??"Bank import"),merchant:String(lower.merchant??lower.payee??"Bank transaction"),category:String(lower.category??"Uncategorized"),amount:Math.abs(amount),type:String(lower.type??"").toLowerCase()==="income"||amount<0?"income":"expense",date:String(lower.date??new Date().toISOString().slice(0,10)),paymentType:"Bank account"}}).filter(item=>item.amount>0);const response=await fetch(`/api/bank-connections/${connection.id}/sync`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transactions})});if(!response.ok)throw new Error(await message(response,"Bank import failed."));setNotice(`${transactions.length} bank records processed.`);await load()}catch(error){setNotice((error as Error).message)}}
 async function runReminders(){const response=await fetch("/api/reminders",{method:"PUT"});if(!response.ok)return setNotice(await message(response,"Reminder generation failed."));const result=await response.json() as {generated:number};setNotice(`${result.generated} due reminder${result.generated===1?"":"s"} generated.`)}
 async function exportData(){const response=await fetch("/api/account/export",{method:"POST"});if(!response.ok)return setNotice(await message(response,"Export failed."));const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="fintrack-export.json";link.click();URL.revokeObjectURL(url)}
 async function governance(action:string,toUserId?:string){const response=await fetch("/api/account/governance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,toUserId})});if(!response.ok)return setNotice(await message(response,"Account action failed."));setNotice(action==="request_deletion"?"Deletion scheduled after the seven-day grace period.":"Request created.")}
 async function decideTransfer(id:string,decision:"accept"|"reject"){const response=await fetch(`/api/account/governance/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision})});if(!response.ok)return setNotice(await message(response,"Ownership decision failed."));await load()}
 const tabs=["upcoming","recurring","subscriptions","banks","audit","governance"];
 return <section className="operations-workspace">{notice&&<div className="inline-notice"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={15}/></button></div>}<div className="operations-tabs">{tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div>
 {tab==="upcoming"&&<section className="workspace-panel"><div className="section-header"><div><h2>Upcoming obligations</h2><p>Liability payments, recurring bills, and renewals due within 31 days.</p></div><button className="secondary-button" onClick={()=>void runReminders()}><Activity size={15}/> Generate reminders</button></div><div className="operations-list">{upcoming.map(item=><article key={`${item.type}-${item.id}`}><div><strong>{item.name}</strong><span>{item.type.replaceAll("_"," ")} · due {new Date(`${item.dueDate}T12:00:00`).toLocaleDateString()}</span></div><strong>{currency.format(item.amount)}</strong></article>)}</div></section>}
 {tab==="recurring"&&<section className="workspace-panel"><div className="section-header"><div><h2>Recurring detection</h2><p>Patterns inferred from matching merchants and transaction intervals.</p></div><button className="secondary-button" onClick={()=>void detect()}><RefreshCw size={15}/> Scan ledger</button></div><div className="operations-list">{patterns.map(item=><article key={item.id}><div><strong>{item.merchant}</strong><span>{item.category} · {item.frequency} · {Math.round(item.confidence*100)}% confidence</span></div><strong>{currency.format(item.averageAmount)}</strong>{item.status==="detected"&&<div><button onClick={()=>void managePattern(item.id,"confirm")}><Check size={15}/></button><button onClick={()=>void managePattern(item.id,"dismiss")}><X size={15}/></button></div>}</article>)}</div></section>}
 {tab==="subscriptions"&&<section className="workspace-panel"><div className="section-header"><div><h2>Subscriptions</h2><p>Track renewal dates, pauses, and cancellations.</p></div><Repeat2 size={19}/></div><form className="operations-form" onSubmit={addSubscription}><input name="name" placeholder="Plan name" required/><input name="vendor" placeholder="Vendor" required/><input name="category" placeholder="Category" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" required/><select name="frequency"><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="weekly">Weekly</option><option value="quarterly">Quarterly</option></select><input name="startDate" type="date" required/><input name="renewalDate" type="date" required/><button className="primary-button"><PlusIcon/> Add</button></form><div className="operations-list">{subscriptions.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.vendor} · renews {new Date(`${item.renewalDate}T12:00:00`).toLocaleDateString()} · {item.status}</span></div><strong>{currency.format(item.amount)}</strong><div><button onClick={()=>void updateSubscription(item.id,item.status==="paused"?"active":"paused")}>{item.status==="paused"?"Resume":"Pause"}</button><button onClick={()=>void updateSubscription(item.id,"cancelled")}>Cancel</button></div></article>)}</div></section>}
 {tab==="banks"&&<section className="workspace-panel"><div className="section-header"><div><h2>Bank imports</h2><p>Provider-neutral connection metadata; credentials stay with your bank integration provider.</p></div><Building2 size={19}/></div><form className="operations-form bank-form" onSubmit={addBank}><input name="provider" placeholder="Provider" required/><input name="externalAccountId" placeholder="External account ID" required/><input name="displayName" placeholder="Display name" required/><select name="accountId" defaultValue=""><option value="">Unlinked</option>{accounts.map(account=><option value={account.id} key={account.id}>{account.name}</option>)}</select><button className="primary-button"><PlusIcon/> Connect</button></form><div className="operations-list">{banks.map(item=><article key={item.id}><div><strong>{item.displayName}</strong><span>{item.provider} · {item.status} · {item.accountName??"unlinked"}</span></div><label className="secondary-button"><FileUp size={15}/> Import<input type="file" accept=".csv,.xlsx,.xls" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void importBank(item,file)}}/></label></article>)}</div></section>}
 {tab==="audit"&&<section className="workspace-panel"><div className="section-header"><div><h2>Audit history</h2><p>Household actions and their authenticated actors.</p></div><ShieldCheck size={19}/></div><div className="audit-table">{audits.map(item=><article key={item.id}><span>{new Date(item.createdAt).toLocaleString()}</span><strong>{item.actor}</strong><span>{item.action}</span><span>{item.entityType}</span><code>{item.entityId}</code></article>)}</div></section>}
 {tab==="governance"&&<section className="workspace-panel"><div className="section-header"><div><h2>Data and ownership</h2><p>Export household data, transfer ownership, or schedule account deletion.</p></div><Download size={19}/></div><div className="governance-actions"><button className="secondary-button" onClick={()=>void exportData()}><Download size={15}/> Export JSON</button>{household?.role==="OWNER"&&<label><span>Transfer ownership</span><select defaultValue="" onChange={event=>{if(event.target.value)void governance("transfer_ownership",event.target.value)}}><option value="" disabled>Select member</option>{household.members.filter(item=>item.role!=="OWNER").map(item=><option value={item.userId} key={item.userId}>{item.name}</option>)}</select></label>}{governanceData?.deletion?<button className="secondary-button" onClick={()=>void governance("cancel_deletion")}>Cancel deletion</button>:<button className="danger-button" onClick={()=>void governance("request_deletion")}><Trash2 size={15}/> Schedule account deletion</button>}</div>{governanceData?.transfers.map(item=><article className="ownership-request" key={item.id}><span>Ownership transfer from {item.fromUser.name??item.fromUser.email} to {item.toUser.name??item.toUser.email}</span><div><button onClick={()=>void decideTransfer(item.id,"accept")}>Accept</button><button onClick={()=>void decideTransfer(item.id,"reject")}>Reject</button></div></article>)}</section>}
 </section>
}
function PlusIcon(){return <span aria-hidden="true">+</span>}
